### ISSUE TITLE
heroku-container-registry is blacklisted

### ISSUE THREAD

**Issue by paganotoni** [markbates/buffalo-heroku#5]
It was moved to the heroku CLI, we may need to check the heroku cli version and warn if lower than certain version.

**Comment by markbates** [comment]
Do you know how to fix this? I’ve been hitting this for a week or so and Travis has been zero help!

**Comment by paganotoni** [comment]
Yes, its because we're trying to install that plugin. I can fix it by avoiding installing that.
I also wonder if we should handle the case where the user doesn't have a version of heroku-cli that has the container part inside and at least show an error saying heroku version needs to be updated, WDYT?

**Comment by markbates** [comment]
Of course. Make it work, please. :)
